# Default values for sonarr.

sonarr:
  image:
    organization: itscontained
    repository: sonarr
    pullPolicy: IfNotPresent
    tag: 3.0.3.913
  service:
    port: 8989
  configPath: /var/lib/radarr
