# Default values for PhotoPrism.

image:
  repository: photoprism/photoprism
  pullPolicy: IfNotPresent
  tag: "20201122"

strategy:
  type: Recreate

service:
  port:
    port: 2342

env: {}
  # PHOTOPRISM_ADMIN_PASSWORD: "please-change"     # Initial admin password: PLEASE CHANGE!
  # PHOTOPRISM_DEBUG: "false"                      # Run in debug mode (shows additional log messages)
  # PHOTOPRISM_PUBLIC: "false"                     # No authentication required (disables password protection)
  # PHOTOPRISM_READONLY: "false"                   # Don't modify originals directory (reduced functionality)
  # PHOTOPRISM_UPLOAD_NSFW: "true"                 # Allow uploads that MAY be offensive
  # PHOTOPRISM_DETECT_NSFW: "false"                # Flag photos as private that MAY be offensive
  # PHOTOPRISM_EXPERIMENTAL: "false"               # Enable experimental features
  # PHOTOPRISM_SITE_URL: "http://localhost:2342/"  # Canonical / public site URL
  # PHOTOPRISM_SITE_TITLE: "PhotoPrism"
  # PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
  # PHOTOPRISM_SITE_DESCRIPTION: ""
  # PHOTOPRISM_SITE_AUTHOR: ""
  # PHOTOPRISM_HTTP_HOST: "0.0.0.0"
  # PHOTOPRISM_HTTP_PORT: 2342
  # PHOTOPRISM_SETTINGS_HIDDEN: "false"            # Users can not view or change settings
  # PHOTOPRISM_DATABASE_DRIVER: "sqlite"           # SQLite is an embedded database that doesn't require a server
  # PHOTOPRISM_DATABASE_DRIVER: "mysql"            # Use MariaDB (or MySQL) instead of SQLite for improved performance
  # PHOTOPRISM_DATABASE_DSN: "photoprism:insecure@tcp(mariadb:3306)/photoprism?charset=utf8mb4,utf8&parseTime=true"
  # PHOTOPRISM_SIDECAR_JSON: "true"                # Automatically create JSON sidecar files using Exiftool
  # PHOTOPRISM_SIDECAR_YAML: "true"                # Automatically backup metadata to YAML sidecar files
  # PHOTOPRISM_THUMB_FILTER: "lanczos"             # Resample filter, best to worst: blackman, lanczos, cubic, linear
  # PHOTOPRISM_THUMB_UNCACHED: "false"             # Enable on-demand thumbnail rendering (high memory and cpu usage)
  # PHOTOPRISM_THUMB_SIZE: 2048                    # Pre-rendered thumbnail size limit (default 2048, min 720, max 7680)
  # # PHOTOPRISM_THUMB_SIZE: 4096                  # Retina 4K, DCI 4K (requires more storage); 7680 for 8K Ultra HD
  # PHOTOPRISM_THUMB_SIZE_UNCACHED: 7680           # On-demand rendering size limit (default 7680, min 720, max 7680)
  # PHOTOPRISM_JPEG_SIZE: 7680                     # Size limit for converted image files in pixels (720-30000)
  # PHOTOPRISM_JPEG_QUALITY: 92                    # Set to 95 for high-quality thumbnails (25-100)
  # PHOTOPRISM_DARKTABLE_PRESETS: "false"          # Use darktable presets (disables concurrent raw to jpeg conversion)
  # # You may optionally set user, group and/or file permissions using environment variables:
  # UID: 1000
  # GID: 1000
  # UMASK: 0000

persistence:
  storage:
    enabled: false
    emptyDir: false
    mountPath: /photoprism/storage

  originals:
    enabled: false
    emptyDir: false
    mountPath: /photoprism/originals
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    # storageClass: "-"
    # accessMode: ReadWriteOnce
    # size: 1Gi
    ## Do not delete the pvc upon helm uninstall
    # skipuninstall: false
    # existingClaim: ""
