apiVersion: v1
kind: Service
metadata:
  name: {{ template "media-common.fullname" . }}-bittorrent
  labels:
  {{- include "media-common.labels" . | nindent 4 }}
  {{- if .Values.qbittorrent.btService.labels }}
  {{ toYaml .Values.qbittorrent.btService.labels | indent 4 }}
  {{- end }}
  {{- with .Values.qbittorrent.btService.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.qbittorrent.btService.type }}
  ports:
    - name: bittorrent
      port: {{ .Values.qbittorrent.btService.port }}
      protocol: TCP
      targetPort: {{ .Values.qbittorrent.btService.port }}
      {{- if (and (eq .Values.qbittorrent.btService.type "NodePort") (not (empty .Values.qbittorrent.btService.nodePort))) }}
      nodePort: {{ .Values.qbittorrent.btService.nodePort }}
      {{- end }}
  {{- with .Values.qbittorrent.btService.additionalSpec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  selector:
  {{- include "media-common.selectorLabels" . | nindent 4 }}
