apiVersion: v2
name: speedtest-prometheus
description: Prometheus Exporter for the official Speedtest CLI
type: application
version: 1.0.0
appVersion: 1.1.0
keywords:
- speedtest
- influxdb
- grafana
home: https://github.com/billimek/billimek-charts/tree/master/charts/speedtest-prometheus
icon: https://img.favpng.com/12/7/24/speedtest-net-logo-internet-access-png-favpng-yVPchiKuhWWAXA41Vpak0NUvx.jpg
sources:
- https://github.com/billimek/prometheus-speedtest-exporter
maintainers:
- name: billimek
  email: jeff@billimek.com
