apiVersion: v2
name: speedtest-prometheus
description: Prometheus Exporter for the official Speedtest CLI
type: application
version: 1.0.1
appVersion: 1.1.0
keywords:
- speedtest
- influxdb
- grafana
home: https://github.com/billimek/billimek-charts/tree/master/charts/speedtest-prometheus
icon: https://cdn.speedcheck.org/images/reviews/ookla-logo.png
sources:
- https://github.com/billimek/prometheus-speedtest-exporter
maintainers:
- name: billimek
  email: jeff@billimek.com
