apiVersion: v1
appVersion: amd64-0.2.0.1318-ls6
description: Radarr is a movie downloading client
name: radarr
version: 1.0.0
keywords:
  - radarr
  - usenet
  - bittorrent
home: https://github.com/Radarr/Radarr/
icon: https://avatars3.githubusercontent.com/u/25025331?s=400&v=4
sources:
  - https://hub.docker.com/r/linuxserver/radarr/
  - https://github.com/billimek/billimek-charts/radarr
maintainers:
  - name: billimek
    email: jeff@billimek.com
