apiVersion: v1
appVersion: v0.12.1132-ls37
description: API Support for your favorite torrent trackers
name: jackett
version: 1.0.1
keywords:
  - jackett
  - torrent
home: https://github.com/billimek/billimek-charts/tree/master/jackett
icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/jackett-banner.png
sources:
  - https://hub.docker.com/r/linuxserver/jackett/
  - https://github.com/Jackett/Jackett
maintainers:
  - name: billimek
    email: jeff@billimek.com
