apiVersion: v1
kind: Service
metadata:
  name: {{ include "blocky.fullname" . }}-headless
  labels:
    app.kubernetes.io/name: {{ include "blocky.name" . }}
    helm.sh/chart: {{ include "blocky.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
  - name: monitoring
    port: 4000
    targetPort: monitoring
  selector:
    app.kubernetes.io/name: {{ include "blocky.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
