apiVersion: v2
name: ombi
description: Want a Movie or TV Show on Plex or Emby? Use Ombi!
type: application
version: 4.0.0
appVersion: 4.0.471
keywords:
  - ombi
home: https://github.com/k8s-at-home/charts/tree/master/charts/ombi
sources:
  - https://github.com/tidusjar/Ombi
  - https://hub.docker.com/r/itscontained/ombi
maintainers:
  - name: DirtyCajunRice
    email: nick@cajun.pro
dependencies:
  - name: media-common
    repository: https://k8s-at-home.com/charts/
    version: ~1.0.0
    alias: ombi
