{{- if .Values.ingress.enabled -}}
  {{- $kubeVersion := .Capabilities.KubeVersion.GitVersion -}}
  {{- $fullName := include "media-common.fullname" . -}}
  {{- $svcPort := .Values.service.port -}}
  {{- if semverCompare ">= 1.19-0" $kubeVersion -}}
apiVersion: networking.k8s.io/v1
  {{- else if semverCompare ">= 1.14-0 < 1.19-0" $kubeVersion -}}
apiVersion: networking.k8s.io/v1beta1
  {{- else -}}
apiVersion: extensions/v1beta1
  {{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
  {{- include "media-common.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if semverCompare ">= 1.14-0" $kubeVersion}}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">= 1.19-0" $kubeVersion}}
              service:
                name: {{ $fullName }}
                port:
                  name: http
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
  {{- end }}
  {{- range $index, $ingress := .Values.ingress.extraIngresses }}
---
  {{- if semverCompare ">= 1.19-0" $kubeVersion -}}
apiVersion: networking.k8s.io/v1
  {{- else if semverCompare ">= 1.14-0 < 1.19-0" $kubeVersion -}}
apiVersion: networking.k8s.io/v1beta1
  {{- else -}}
apiVersion: extensions/v1beta1
    {{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ $ingress.nameSuffix | default $index }}
  labels:
    {{- include "media-common.labels" . | nindent 4 }}
    {{- with $ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $ingress.tls }}
  tls:
    {{- range $ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
    {{- range $ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if semverCompare ">= 1.14-0" $kubeVersion}}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">= 1.19-0" $kubeVersion}}
              service:
                name: {{ $fullName }}
                port:
                  name: http
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
